# .github/workflows/nightly.yml
name: nightly

on:
  push:
    branches:
      - "master"

jobs:
  go:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu

          - os: macos-latest
            target: x86_64-apple-darwin

          - os: windows-latest
            target: x86_64-pc-windows-msvc
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download Rust Build Artifacts
        uses: robinraju/release-downloader@v1.10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          preRelease: true
          tag: "nightly"
          repository: "FKU-bilimall/biliTicker_gt"
          fileName: "*"
          out-file-path: captcha/biliTicker/target/${{ matrix.target }}/release

      - name: Download release
        uses: robinraju/release-downloader@v1.10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          preRelease: true
          tag: "nightly"
          repository: "FKU-bilimall/biliTicker_gt"
          fileName: "bindings.h"
          out-file-path: "captcha/biliTicker/"

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: stable

      - name: Build and Package Go Binary
        run: python3 build.py --target ${{ matrix.target }} --deps captcha/biliTicker/target/${{ matrix.target }}/release

      - name: Upload Go Binary Zip
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.target }}
          path: output/bilibili-ticket-go_*.zip

  release:
    needs: [go]
    runs-on: ubuntu-latest
    steps:
      - name: Download all Go Binary Zips
        uses: actions/download-artifact@v5
        with:
          pattern: build-*
          path: release_zips

      - name: Display structure of release files
        run: ls -R release_zips

      - name: Publish Nightly
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "nightly"
          draft: false
          prerelease: true
          title: "Nightly updates"
          files: |
            release_zips/**/*.zip
