# .github/workflows/nightly.yml
name: nightly

on:
  push:
    branches:
      - "master"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-btg
          restore-keys: |
            ${{ runner.os }}-go-btg

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: stable
        
      # More assembly might be required: Docker logins, GPG, etc.
      # It all depends on your needs.
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          # 'latest', 'nightly', or a semver
          args: --snapshot --clean
          
      - name: Publish Nightly
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "nightly"
          draft: false
          prerelease: true
          title: "Nightly updates"
          files: |
            dist/*.zip
            dist/checksums.txt
